202209142210
Tags:
___
# Конструкция try...except...finally
При программировании на Python мы можем столкнуться с двумя типами ошибок. Первый тип представляют **синтаксические ошибки (syntax error)**. Они появляются в результате нарушения синтаксиса языка программирования при написании исходного кода. При наличии таких ошибок программа не может быть скомпилирована. При работе в какой-либо среде разработки, например, в PyCharm, IDE сама может отслеживать синтаксические ошибки и каким-либо образом их выделять.

Второй тип ошибок представляют **ошибки выполнения (runtime error)**. Они появляются в уже скомпилированной программе в процессе ее выполнения. Подобные ошибки еще называются **исключениями.** 

При возникновении исключения работа программы прерывается, и чтобы избежать подобного поведения и обрабатывать исключения в Python есть конструкция `try..except`.

Конструкция:
```python
try:
	инструкции
except [Тип_исключения]:
	инструкции
else: 
	инструкции
finally:
	инструкции
```

**try** - содержит основной код, в котором потенциально может возникнуть исключение.
**except** - Если в этом коде генерируется исключение, то работа кода в блоке try прерывается, и выполнение переходит в блок except. После ключевого слова except опционально можно указать, какое исключение будет обрабатываться (например, ValueError или KeyError). 
**else** - опциональный блок, выполняется в том случае, если не было исключения.
**finally** - опциональный блок, выполняется **всегда**, независимо от того, было ли исключение или нет.

```python
try:
    a = input("Введите первое число: ")
    b = input("Введите второе число: ")
    result = int(a)/int(b)
except (ValueError, ZeroDivisionError):
    print("Что-то пошло не так...")
else:
    print("Результат в квадрате: ", result**2)
finally:
    print("Вот и сказочке конец, а кто слушал - молодец.")
```

Проверка:
```python 
Введите первое число: 10
Введите второе число: 2
Результат в квадрате:  25
Вот и сказочке конец, а кто слушал - молодец.

Введите первое число: qwerewr
Введите второе число: 3
Что-то пошло не так...
Вот и сказочке конец, а кто слушал - молодец.

Введите первое число: 4
Введите второе число: 0
Что-то пошло не так...
Вот и сказочке конец, а кто слушал - молодец.
```

# Генерация исключений и оператор raise
Иногда возникает необходимость вручную сгенерировать то или иное исключение. Для этого применяется оператор **raise**. Например, сгенерируем исключение

```python
try:
    number1 = int(input("Введите первое число: "))
    number2 = int(input("Введите второе число: "))
    if number2 == 0:
        raise Exception("Второе число не должно быть равно 0")
    print("Результат деления двух чисел:", number1/number2)
except ValueError:
    print("Введены некорректные данные")
except Exception as e:
    print(e)
print("Завершение программы")
```
Оператору raise передается объект BaseException - в данном случае объект Exception. В конструктор этого типа можно ему передать сообщение, которое затем можно вывести пользователю. В итоге, если number2 будет равно 0, то сработает оператор raise, который сгенерирует исключение. В итоге управление программой перейдет к блоку except, который обрабатывает исключения типа Exception:


# Встроенные типы исключений
В Python есть следующие базовые типы исключений:
-   **BaseException**: базовый тип для всех встроенных исключений
-   **Exception**: базовый тип, который обычно применяется для создания своих типов исключений
-   **ArithmeticError**: базовый тип для исключений, связанных с арифметическими операциями (OverflowError, ZeroDivisionError, FloatingPointError).
-   **BufferError**: тип исключения, которое возникает при невозможности выполнить операцию с буффером
-   **LookupError**: базовый тип для исключений, которое возникают при обращении в коллекциях по некорректному ключу или индексу (например, IndexError, KeyError)

От этих классов наследуются все конкретные типы исключений. В Python обладает довольно большим списком встроенных исключений. Весь этот список можно посмотреть в [документации](https://docs.python.org/3/library/exceptions.html). Перечислю только некоторые наиболее часто встречающиеся:

-   **IndexError**: исключение возникает, если индекс при обращении к элементу коллекции находится вне допустимого диапазона
-   **KeyError**: возникает, если в словаре отсутствует ключ, по которому происходит обращение к элементу словаря.
-   **OverflowError**: возникает, если результат арифметической операции не может быть представлен текущим числовым типом (обычно типом float).
-   **RecursionError**: возникает, если превышена допустимая глубина рекурсии.
-   **TypeError**: возникает, если операция или функция применяется к значению недопустимого типа.
-   **ValueError**: возникает, если операция или функция получают объект корректного типа с некорректным значением.
-   **ZeroDivisionError**: возникает при делении на ноль.
-   **NotImplementedError**: тип исключения для указания, что какие-то методы класса не реализованы
-   **ModuleNotFoundError**: возникает при при невозможности найти модуль при его импорте директивой `import`
-   **OSError**: тип исключений, которые генерируются при возникновении ошибок системы (например, невозможно найти файл, память диска заполнена и т.д.)

И если ситуация такова, что в программе могут быть сгенерированы различные типы исключений, то мы можем их обработать по отдельности, используя дополнительные выражения except. И при возникновении исключения Python будет искать нужный блок except, который обрабатывает данный тип исключения:

```python
try:
    number1 = int(input("Введите первое число: "))
    number2 = int(input("Введите второе число: "))
    print("Результат деления:", number1/number2)
except ValueError:
    print("Преобразование прошло неудачно")
except ZeroDivisionError:
    print("Попытка деления числа на ноль")
except BaseException:
    print("Общее исключение")
print("Завершение программы")
```

Python позволяет в одном блоке except обрабатывать сразу несколько типов исключений. В этом случае все типы исключения передаются в скобках:

```python
try:
    number1 = int(input("Введите первое число: "))
    number2 = int(input("Введите второе число: "))
    print("Результат деления:", number1/number2)
except (ZeroDivisionError, ValueError):    #  обработка двух типов исключений - ZeroDivisionError и ValueError
    print("Попытка деления числа на ноль или некорректный ввод")
 
print("Завершение программы")
```

## Получение информации об исключении
С помощью оператора as мы можем передать всю информацию об исключении в переменную, которую затем можно использовать в блоке except:

```python
try:
    number = int(input("Введите число: "))
    print("Введенное число:", number)
except ValueError as e:
    print("Сведения об исключении", e)
print("Завершение программы")
```
Пример некорректного ввода:
```bash
Введите число: fdsf
Сведения об исключении invalid literal for int() with base 10: 'fdsf'
Завершение программы
```


# Создание своих типов исключений
В языке Python мы не ограничены только встроенными типами исключений и можем, применяя наследование, при необходимости создавать свои типы исключений. Например, возьмем следующий класс Person:

```python
class Person:
    def __init__(self, name, age):
        self.__name = name  # устанавливаем имя
        self.__age = age   # устанавливаем возраст
 
    def display_info(self):
        print(f"Имя: {self.__name}  Возраст: {self.__age}")
```
Здесь класс Person в конструкторе получает значения для имени и возраста и присваивает их приватным переменным name и age. Однако при создании объекта Person мы можем передать в конструктор некорректное с точки зрения логики значение - например, отрицательное число. Одним из способов решения данной ситуации представляет генерация исключения при передаче некорректных значений.

Итак, определим следующий код программы:

```python
'''
В начале здесь определен класс PersonAgeException, который наследуется от класса
Exception. Как правило, собственные классы исключений наследуются от класса Exception.
Класс PersonAgeException предназначен для исключений, связанных с возрастом пользователя.

В конструкторе PersonAgeException получаем три значения - собственное некорректное
значение, которое послужило причиной исключения, а также минимальное и максимальное
значения возраста.
'''
class PersonAgeException(Exception):
    def __init__(self, age, minage, maxage):
        self.age = age
        self.minage = minage
        self.maxage = maxage
        
 '''В функции __str__ определяем текстовое представление класса - по сути сообщение об
 ошибке.'''
 
    def __str__(self):
        return f"Недопустимое значение: {self.age}. " \
               f"Возраст должен быть в диапазоне от {self.minage} до {self.maxage}"


'''В конструкторе класса Persoon проверяем переданное для возраста пользователя значение.
И если это значение не соответствует определенному диапазону, то генерируем исключение
типа PersonAgeException:
'''
class Person:
    def __init__(self, name, age):
        self.__name = name  # устанавливаем имя
        minage, maxage = 1, 110
        if minage < age < maxage:   # устанавливаем возраст, если передано корректное значение
            self.__age = age
        else:                       # иначе генерируем исключение
            raise PersonAgeException(age, minage, maxage)
 
    def display_info(self):
        print(f"Имя: {self.__name}  Возраст: {self.__age}")

'''
При применении класса Person нам следует учитывать, что конструктор класса может
сгенерировать исключение при передаче некорректного значения. Поэтому создание объектов
Person обертывается в конструкцию try..except:
'''
try:
    tom = Person("Tom", 37)
    tom.display_info()  # Имя: Tom  Возраст: 37
 
    bob = Person("Bob", -23)
    bob.display_info()
except PersonAgeException as e:
    print(e)    # Недопустимое значение: -23. Возраст должен быть в диапазоне от 1 до 110

'''
И если при вызове конструктора Person будет сгенерировано исключение типа
PersonAgeException, то управление программой перейдет к блоку except, который
обрабатывает исключения типа PersonAgeException в виде вывода информации об исключении на
консоль.
'''
```




# Ссылки
___
##### Links


---
##### Источники
https://pythonworld.ru/tipy-dannyx-v-python/isklyucheniya-v-python-konstrukciya-try-except-dlya-obrabotki-isklyuchenij.html

https://metanit.com/python/tutorial/2.11.php
https://metanit.com/python/tutorial/2.21.php
https://pyneng.readthedocs.io/ru/latest/book/06_control_structures/exceptions.html